# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build docker file
        run: docker build . -t ahadalichowdhury/testing-nodejs
      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      - name: Push to Dockerhub
        run: docker push ahadalichowdhury/testing-nodejs
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: pull docker image
        runs-on: [ip-172-31-22-138]
        steps:
          - uses: actions/checkout@v2
          - name: pull docker image
            run: docker pull ahadalichowdhury/testing-nodejs
          - name: delete old container
            run: docker rm -f nodejs-app-container
          - name: run docker image
            run: docker run -d -p 6001:5000 --name nodejs-app-container ahadalichowdhury/testing-nodejs
